# Generated by Django 3.1.2 on 2021-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0064_add_job_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="will_notify",
            field=models.BooleanField(default=False),
        ),
    ]
